[project]
name = "stock-investment"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13,<3.14"
dependencies = [
    "fastapi>=0.139.2",
    "httpx>=0.28.1",
    "kgisuperpy>=2.0.8",
    "openpyxl>=3.1.5",
    "pandas>=3.0.5",
    "python-docx>=1.2.0",
    "python-dotenv>=1.2.2",
    "reportlab>=5.0.0",
    "requests>=2.34.2",
    "uvicorn>=0.51.0",
    "yfinance>=1.5.2",
]
